### ISSUE TITLE
Edge remover via batch file doesn't work

### ISSUE THREAD

**Issue by TommyCowley101** [ShadowWhisperer/Remove-MS-Edge#71]
when trying to uninstall edge via the batch file it pops a window up saying its "downloading required files" then shuts off immediately after and edge is still installed, i have also tried it with the setup.exe you recommended and it still fails saying "windows cannot find --uninstall make sure you've typed the name correctly, then try again" it also fails to uninstall edge, this also applies to the both.bat script which is meant to remove edge and webview, i should add all tests was done with a internet connection 
![Capture](https://github.com/user-attachments/assets/9a1a4bef-3d52-4a94-b48b-2c72845488fb)

**Comment by ShadowWhisperer** [comment]
Should be fixed.

**Comment by TommyCowley101** [comment]
@ShadowWhisperer  wow thanks so much, appreciate the quick response and fix :)))

**Comment by XakerTwo** [comment]
not fixed - any whitespace and it's broken gain

just type `start /?` in cmd to read help, and return removed quotes

**Comment by ShadowWhisperer** [comment]
I did not know that's how it worked. Thanks!
I wondered why putting quotes would error out.
Updated.

Thank you!
